name: Frontend release

on:
  push:
    tags:
      - "frontend-v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'
          channel: 'stable'

      - name: Build
        run: |
          cd frontend
          flutter pub get
          flutter build web --base-href /app/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "frontend/build/web"
          generate_release_notes: true