name: Frontend deploy

on:
    release:
        types: [published]

concurrency: Frontend deploy

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Checkout latest release tag
              run: |
                LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
                git checkout $LATEST_TAG
            - name: Install
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.13.2'
                channel: 'stable'

            - name: Build
              run: |
                cd frontend
                flutter pub get
                flutter build web --base-href /app/
